(CPR-407) Enable packaging to ship fedora packages to repos not prepended with f
puppetlabs/build-data pull request #87
Opened 2017-05-18 22:17 UTC by mwaggett

This commit removes the f before the version number for fedora platforms.

2017-05-18 22:26 UTC, mwaggett commented
Waiting for beaker's end of [RE-8333](https://tickets.puppetlabs.com/browse/RE-8333).

2017-05-19 04:00 UTC, puppetcla commented
CLA signed by all contributors.

2017-07-06 18:01 UTC, underscorgan requested changes

2017-07-06 18:01 UTC, underscorgan commented on builder_data.yaml
> +  - fedora-25-x86_64
Can this be additive so we can still ship f prefixed platforms if they exist?

2017-07-06 21:21 UTC, underscorgan approved these changes

2017-07-06 23:49 UTC, merged